###
POST http://localhost:3000/api/client HTTP/1.1
Content-Type: application/json

{
    "name":"Client 1",
    "lastname":"lastname 1",
    "age":31,
    "email":"Client@ucaldas.edu.co",
    "address":{
        "city":"Manizales",
        "zode_zip":"170001",
        "lat":-75.488777,
        "len":5.086858
    }
}

###
POST http://localhost:3000/api/product HTTP/1.1
Content-Type: application/json

{
    "product":"cafetera",
    "img":"https://images.pexels.com/photos/1271940/pexels-photo-1271940.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "price":340000,
    "cant":5,
    "state":true
}

###

GET http://localhost:3000/api/user HTTP/1.1

###

GET http://localhost:3000/api/user/6213bdec2c39cba47f442101 HTTP/1.1

//Reemplazar id por id especifica
DELETE http://localhost:3000/api/user/id HTTP/1.1

//Reemplazar id por id especifica
PUT http://localhost:3000/api/user/id HTTP/1.1
Content-Type: application/json

{
    "name":"Esteban",
    "lastname":"Giraldo"
}